export const PRODUCTS_CATALOG = {
  "Avella": [
    { name: "Столешка (1250х650)", hasColor: true },
    { name: "Обвязка (1158х50)", hasColor: true },
    { name: "Обвязка (600х50)", hasColor: true },
    { name: "Дно (320х568)", hasColor: false },
    { name: "Бок (360х568)", hasColor: true },
    { name: "Фасад (396х305)", hasColor: true },
    { name: "Перегородка", hasColor: true },
    { name: "Полка", hasColor: true },
  ],
  "Avella lite": [
    { name: "Столешка (1250х650)", hasColor: true },
    { name: "Обвязка (1158х50)", hasColor: true },
    { name: "Обвязка (600х50)", hasColor: true },
    { name: "Дно (320х568)", hasColor: false },
    { name: "Бок (360х568)", hasColor: true },
  ],
  "Stabile": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Задняя стенка", hasColor: false },
  ],
  "Solito": [
    { name: "Столешка", hasColor: true },
    { name: "Бок (левый)", hasColor: true },
    { name: "Бок (правый)", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Фасад", hasColor: true },
    { name: "Полка средняя", hasColor: true },
  ],
  "Solito2": [
    { name: "Столешка", hasColor: true },
    { name: "Бок (левый)", hasColor: true },
    { name: "Бок (правый)", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Фасад", hasColor: true },
    { name: "Перегородка", hasColor: true },
    { name: "Полка", hasColor: true },
  ],
  "Cremona": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина", hasColor: true },
    { name: "Фасад верхний", hasColor: true },
    { name: "Фасад нижний", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Классико": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
  ],
  "Классико +": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Фасад нижний", hasColor: true },
    { name: "Фасад верхний", hasColor: true },
    { name: "Полка", hasColor: true },
  ],
  "Donini Grande": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Donini 806": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Donini 750": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Donini R 750": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Donini R 806": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "ТВ Лофт": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Задняя стенка", hasColor: false },
  ],
  "ТВ Лофт 1500": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Перегородка", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Задняя стенка", hasColor: false },
  ],
  "TV Siena": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
  "Премьер": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Перегородка", hasColor: true },
    { name: "Дно", hasColor: false },
    { name: "Задняя стенка", hasColor: false },
  ],
  "Премьер белый": [
    { name: "Столешка", hasColor: true },
    { name: "Боковина левая", hasColor: true },
    { name: "Боковина правая", hasColor: true },
    { name: "Фасад", hasColor: true },
    { name: "Полка", hasColor: true },
    { name: "Дно", hasColor: false },
  ],
};

export const COLORS_LIST = [
  "Белый",
  "Дуб Сонома",
  "Венге",
  "Дуб Вотан",
  "Дуб Крафт",
  "Дуб Сантана",
  "Дуб Небраска",
  "Дуб Эврика",
  "Дуб Гавана",
  "Орех Экко",
  "Ясень Шимо",
  "Бетон Чикаго",
  "Антрацит",
  "Серый",
  "Черный матовый",
  "Белый матовый",
  "Пиния",
];

export const DEFECT_REASONS = [
  "Брак производства",
  "Скол при транспортировке",
  "Царапина / повреждение",
  "Неправильный раскрой",
  "Потеря детали",
  "Пересортица",
  "Иное",
];
