#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys

from sync_materials_from_gsheet import build_export_url, normalize_name, parse_qty, sql_escape
import csv
import io
import urllib.request


def generate_sql(sheet_id: str, gid: str) -> tuple[str, int]:
    url = build_export_url(sheet_id, gid)
    with urllib.request.urlopen(url) as resp:
        content = resp.read().decode("utf-8-sig", errors="replace")

    reader = csv.reader(io.StringIO(content))
    agg = {}
    for row in reader:
        if len(row) < 5:
            continue
        qty = parse_qty(row[4])  # E
        name = normalize_name(row[3])  # D
        if qty is None or not name:
            continue
        agg[name] = qty

    items = sorted(agg.items(), key=lambda x: x[0])
    lines = [
        "-- Auto-generated by migration/apply_materials_stock_sync.py",
        "-- Source: E=qty, D=material",
        "",
        "with src(material, qty_sheets) as (",
        "  values",
    ]
    for idx, (material, qty) in enumerate(items):
        suffix = "," if idx < len(items) - 1 else ""
        lines.append(f"    ('{sql_escape(material)}', {qty:.2f}){suffix}")
    lines += [
        ")",
        "insert into public.materials_stock(material, qty_sheets)",
        "select material, qty_sheets::numeric(12,2)",
        "from src",
        "on conflict (material) do update",
        "set",
        "  qty_sheets = excluded.qty_sheets,",
        "  updated_at = now();",
        "",
    ]
    return ("\n".join(lines), len(items))


def main():
    parser = argparse.ArgumentParser(
        description="Generate and apply materials_stock sync from Google Sheet (E qty, D material)."
    )
    parser.add_argument("--sheet-id", required=True)
    parser.add_argument("--gid", required=True)
    parser.add_argument(
        "--out",
        default="migration/materials_stock_sync_from_gsheet.sql",
        help="Where to save generated SQL",
    )
    parser.add_argument(
        "--db-url-env",
        default="SUPABASE_DB_URL",
        help="Env var with Postgres connection string for psql",
    )
    parser.add_argument(
        "--no-apply",
        action="store_true",
        help="Only generate SQL, do not execute",
    )
    args = parser.parse_args()

    sql, count = generate_sql(args.sheet_id, args.gid)
    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql)

    print(f"Generated: {args.out}")
    print(f"Rows: {count}")

    if args.no_apply:
        print("Apply skipped (--no-apply).")
        return

    db_url = os.getenv(args.db_url_env, "").strip()
    if not db_url:
        print(
            f"Skip apply: env {args.db_url_env} is not set. "
            f"Run with --no-apply or set {args.db_url_env} and rerun."
        )
        sys.exit(2)

    cmd = ["psql", db_url, "-v", "ON_ERROR_STOP=1", "-f", args.out]
    print("Running:", " ".join(["psql", "<db-url>", "-v", "ON_ERROR_STOP=1", "-f", args.out]))
    result = subprocess.run(cmd, check=False)
    if result.returncode != 0:
        print(f"psql failed with exit code {result.returncode}")
        sys.exit(result.returncode)
    print("Applied successfully.")


if __name__ == "__main__":
    main()
