#!/usr/bin/env python3
import argparse
import csv
import io
import re
import urllib.request


NORMALIZE_MAP = {
    "мрамор кристал": "мрамор кристалл",
    "слоновья кость": "слоновая кость",
    "бардолино": "сонома / бардолино",
    r"сонома\бардолино темная": "сонома / бардолино темная",
}


def normalize_name(raw: str) -> str:
    s = (raw or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    return NORMALIZE_MAP.get(s, s)


def parse_qty(raw: str):
    s = (raw or "").strip().replace(",", ".")
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def build_export_url(sheet_id: str, gid: str) -> str:
    return f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"


def main():
    parser = argparse.ArgumentParser(
        description="Generate SQL sync for materials_stock from Google Sheet (E qty, D material)."
    )
    parser.add_argument("--sheet-id", required=True, help="Google Sheet ID")
    parser.add_argument("--gid", required=True, help="Sheet gid")
    parser.add_argument(
        "--out",
        default="migration/materials_stock_sync_from_gsheet.sql",
        help="Output SQL file path",
    )
    args = parser.parse_args()

    url = build_export_url(args.sheet_id, args.gid)
    with urllib.request.urlopen(url) as resp:
        content = resp.read().decode("utf-8-sig", errors="replace")

    reader = csv.reader(io.StringIO(content))
    agg = {}
    for row in reader:
        if len(row) < 5:
            continue
        qty = parse_qty(row[4])  # column E
        name = normalize_name(row[3])  # column D
        if qty is None or not name:
            continue
        agg[name] = qty

    lines = []
    lines.append("-- Auto-generated by migration/sync_materials_from_gsheet.py")
    lines.append("-- Source: E=qty, D=material")
    lines.append("")
    lines.append("with src(material, qty_sheets) as (")
    lines.append("  values")
    items = sorted(agg.items(), key=lambda x: x[0])
    for idx, (material, qty) in enumerate(items):
        suffix = "," if idx < len(items) - 1 else ""
        lines.append(f"    ('{sql_escape(material)}', {qty:.2f}){suffix}")
    lines.append(")")
    lines.append("insert into public.materials_stock(material, qty_sheets)")
    lines.append("select material, qty_sheets::numeric(12,2)")
    lines.append("from src")
    lines.append("on conflict (material) do update")
    lines.append("set")
    lines.append("  qty_sheets = excluded.qty_sheets,")
    lines.append("  updated_at = now();")

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated: {args.out}")
    print(f"Rows: {len(items)}")


if __name__ == "__main__":
    main()
