-- Separate metal process domain: catalog, work items, stage events and RPCs.

create table if not exists public.metal_product_catalog (
  article text primary key,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.metal_work_items (
  id bigint generated by default as identity primary key,
  article text not null references public.metal_product_catalog(article) on update cascade,
  name text not null,
  week text,
  qty numeric(12,3) not null default 0 check (qty > 0),
  current_stage text not null default 'laser' check (current_stage in ('laser', 'bending', 'welding', 'painting')),
  stage_status text not null default 'queued' check (stage_status in ('queued', 'in_progress', 'paused', 'done')),
  status text not null default 'active' check (status in ('active', 'done', 'cancelled')),
  current_stage_started_at timestamptz,
  created_by uuid null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.metal_stage_events (
  id bigint generated by default as identity primary key,
  work_item_id bigint not null references public.metal_work_items(id) on delete cascade,
  stage text not null check (stage in ('laser', 'bending', 'welding', 'painting')),
  action text not null check (action in ('start', 'pause', 'resume', 'done')),
  actor_user_id uuid null default auth.uid(),
  note text,
  event_at timestamptz not null default now()
);

create index if not exists idx_metal_product_catalog_active on public.metal_product_catalog(is_active, article);
create index if not exists idx_metal_work_items_status on public.metal_work_items(status, current_stage, stage_status, created_at desc);
create index if not exists idx_metal_stage_events_item on public.metal_stage_events(work_item_id, event_at);

create or replace function public.trg_metal_process_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_metal_product_catalog_touch_updated_at on public.metal_product_catalog;
create trigger trg_metal_product_catalog_touch_updated_at
before update on public.metal_product_catalog
for each row
execute function public.trg_metal_process_touch_updated_at();

drop trigger if exists trg_metal_work_items_touch_updated_at on public.metal_work_items;
create trigger trg_metal_work_items_touch_updated_at
before update on public.metal_work_items
for each row
execute function public.trg_metal_process_touch_updated_at();

alter table public.metal_product_catalog enable row level security;
alter table public.metal_work_items enable row level security;
alter table public.metal_stage_events enable row level security;

drop policy if exists metal_product_catalog_read_all on public.metal_product_catalog;
create policy metal_product_catalog_read_all
  on public.metal_product_catalog
  for select
  to authenticated
  using (true);

drop policy if exists metal_product_catalog_write_auth on public.metal_product_catalog;
create policy metal_product_catalog_write_auth
  on public.metal_product_catalog
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

drop policy if exists metal_work_items_read_all on public.metal_work_items;
create policy metal_work_items_read_all
  on public.metal_work_items
  for select
  to authenticated
  using (true);

drop policy if exists metal_work_items_write_auth on public.metal_work_items;
create policy metal_work_items_write_auth
  on public.metal_work_items
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

drop policy if exists metal_stage_events_read_all on public.metal_stage_events;
create policy metal_stage_events_read_all
  on public.metal_stage_events
  for select
  to authenticated
  using (true);

drop policy if exists metal_stage_events_write_auth on public.metal_stage_events;
create policy metal_stage_events_write_auth
  on public.metal_stage_events
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

create or replace function public.web_list_metal_catalog(
  p_active_only boolean default true
)
returns table(
  article text,
  name text,
  is_active boolean,
  updated_at timestamptz
)
language sql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  select
    c.article,
    c.name,
    c.is_active,
    c.updated_at
  from public.metal_product_catalog c
  where not coalesce(p_active_only, true) or c.is_active = true
  order by c.article;
$$;

create or replace function public.web_upsert_metal_catalog_item(
  p_article text,
  p_name text,
  p_is_active boolean default true
)
returns table(
  article text,
  name text,
  is_active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_article text := upper(trim(coalesce(p_article, '')));
  v_name text := trim(coalesce(p_name, ''));
begin
  perform public.web_require_roles(array['manager', 'admin']);
  if v_article = '' then
    raise exception 'article required';
  end if;
  if v_name = '' then
    raise exception 'name required';
  end if;

  insert into public.metal_product_catalog(article, name, is_active)
  values (v_article, v_name, coalesce(p_is_active, true))
  on conflict (article)
  do update set
    name = excluded.name,
    is_active = excluded.is_active,
    updated_at = now();

  perform public.web_audit_log_event(
    'upsert_metal_catalog_item',
    'metal_product_catalog',
    v_article,
    jsonb_build_object(
      'name', v_name,
      'is_active', coalesce(p_is_active, true)
    )
  );

  return query
  select
    c.article,
    c.name,
    c.is_active,
    c.updated_at
  from public.metal_product_catalog c
  where c.article = v_article;
end;
$$;

create or replace function public.web_create_metal_work_item(
  p_article text,
  p_name text,
  p_week text,
  p_qty numeric
)
returns table(
  id bigint,
  article text,
  name text,
  week text,
  qty numeric,
  current_stage text,
  stage_status text,
  status text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_article text := upper(trim(coalesce(p_article, '')));
  v_name text := trim(coalesce(p_name, ''));
  v_week text := nullif(trim(coalesce(p_week, '')), '');
  v_qty numeric := coalesce(p_qty, 0);
begin
  perform public.web_require_roles(array['operator', 'manager', 'admin']);
  if v_article = '' then
    raise exception 'article required';
  end if;
  if v_name = '' then
    raise exception 'name required';
  end if;
  if v_qty <= 0 then
    raise exception 'qty must be > 0';
  end if;

  insert into public.metal_product_catalog(article, name, is_active)
  values (v_article, v_name, true)
  on conflict (article)
  do update set
    name = excluded.name,
    is_active = true,
    updated_at = now();

  return query
  insert into public.metal_work_items(article, name, week, qty, current_stage, stage_status, status)
  values (v_article, v_name, v_week, v_qty, 'laser', 'queued', 'active')
  returning
    metal_work_items.id,
    metal_work_items.article,
    metal_work_items.name,
    metal_work_items.week,
    metal_work_items.qty,
    metal_work_items.current_stage,
    metal_work_items.stage_status,
    metal_work_items.status,
    metal_work_items.created_at,
    metal_work_items.updated_at;

  perform public.web_audit_log_event(
    'create_metal_work_item',
    'metal_work_items',
    currval('public.metal_work_items_id_seq')::text,
    jsonb_build_object(
      'article', v_article,
      'name', v_name,
      'week', v_week,
      'qty', v_qty
    )
  );
end;
$$;

create or replace function public.web_transition_metal_stage(
  p_item_id bigint,
  p_action text
)
returns table(
  id bigint,
  article text,
  name text,
  week text,
  qty numeric,
  current_stage text,
  stage_status text,
  status text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_action text := lower(trim(coalesce(p_action, '')));
  v_item public.metal_work_items%rowtype;
  v_stages text[] := array['laser', 'bending', 'welding', 'painting'];
  v_pos integer;
  v_next_stage text;
begin
  perform public.web_require_roles(array['operator', 'manager', 'admin']);
  if v_action not in ('start', 'pause', 'resume', 'done') then
    raise exception 'unsupported action';
  end if;

  select *
  into v_item
  from public.metal_work_items
  where id = p_item_id
  for update;

  if v_item.id is null then
    raise exception 'work item not found';
  end if;
  if v_item.status in ('done', 'cancelled') then
    raise exception 'work item already completed';
  end if;

  if v_action = 'start' then
    if v_item.stage_status <> 'queued' then
      raise exception 'stage must be queued for start';
    end if;
    update public.metal_work_items
    set
      stage_status = 'in_progress',
      current_stage_started_at = now(),
      updated_at = now()
    where id = v_item.id;
  elsif v_action = 'pause' then
    if v_item.stage_status <> 'in_progress' then
      raise exception 'stage must be in_progress for pause';
    end if;
    update public.metal_work_items
    set
      stage_status = 'paused',
      updated_at = now()
    where id = v_item.id;
  elsif v_action = 'resume' then
    if v_item.stage_status <> 'paused' then
      raise exception 'stage must be paused for resume';
    end if;
    update public.metal_work_items
    set
      stage_status = 'in_progress',
      updated_at = now()
    where id = v_item.id;
  else
    if v_item.stage_status not in ('in_progress', 'paused') then
      raise exception 'stage must be in_progress or paused for done';
    end if;
    v_pos := array_position(v_stages, v_item.current_stage);
    if v_pos is null then
      raise exception 'invalid current stage';
    end if;
    v_next_stage := v_stages[v_pos + 1];
    if v_next_stage is null then
      update public.metal_work_items
      set
        stage_status = 'done',
        status = 'done',
        current_stage_started_at = null,
        updated_at = now()
      where id = v_item.id;
    else
      update public.metal_work_items
      set
        current_stage = v_next_stage,
        stage_status = 'queued',
        current_stage_started_at = null,
        updated_at = now()
      where id = v_item.id;
    end if;
  end if;

  insert into public.metal_stage_events(work_item_id, stage, action)
  values (v_item.id, v_item.current_stage, v_action);

  perform public.web_audit_log_event(
    'transition_metal_stage',
    'metal_work_items',
    v_item.id::text,
    jsonb_build_object(
      'stage', v_item.current_stage,
      'action', v_action
    )
  );

  return query
  select
    i.id,
    i.article,
    i.name,
    i.week,
    i.qty,
    i.current_stage,
    i.stage_status,
    i.status,
    i.created_at,
    i.updated_at
  from public.metal_work_items i
  where i.id = v_item.id;
end;
$$;

create or replace function public.web_list_metal_work_items(
  p_status text default null
)
returns table(
  id bigint,
  article text,
  name text,
  week text,
  qty numeric,
  current_stage text,
  stage_status text,
  status text,
  created_at timestamptz,
  updated_at timestamptz,
  laser_seconds bigint,
  bending_seconds bigint,
  welding_seconds bigint,
  painting_seconds bigint
)
language sql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  with ev as (
    select
      e.work_item_id,
      e.stage,
      e.action,
      e.event_at,
      lead(e.event_at) over (partition by e.work_item_id order by e.event_at) as next_event_at
    from public.metal_stage_events e
  ),
  agg as (
    select
      e.work_item_id,
      sum(
        case
          when e.stage = 'laser' and e.action in ('start', 'resume')
            then greatest(0, extract(epoch from (coalesce(e.next_event_at, now()) - e.event_at)))::bigint
          else 0
        end
      ) as laser_seconds,
      sum(
        case
          when e.stage = 'bending' and e.action in ('start', 'resume')
            then greatest(0, extract(epoch from (coalesce(e.next_event_at, now()) - e.event_at)))::bigint
          else 0
        end
      ) as bending_seconds,
      sum(
        case
          when e.stage = 'welding' and e.action in ('start', 'resume')
            then greatest(0, extract(epoch from (coalesce(e.next_event_at, now()) - e.event_at)))::bigint
          else 0
        end
      ) as welding_seconds,
      sum(
        case
          when e.stage = 'painting' and e.action in ('start', 'resume')
            then greatest(0, extract(epoch from (coalesce(e.next_event_at, now()) - e.event_at)))::bigint
          else 0
        end
      ) as painting_seconds
    from ev e
    group by e.work_item_id
  )
  select
    i.id,
    i.article,
    i.name,
    i.week,
    i.qty,
    i.current_stage,
    i.stage_status,
    i.status,
    i.created_at,
    i.updated_at,
    coalesce(a.laser_seconds, 0) as laser_seconds,
    coalesce(a.bending_seconds, 0) as bending_seconds,
    coalesce(a.welding_seconds, 0) as welding_seconds,
    coalesce(a.painting_seconds, 0) as painting_seconds
  from public.metal_work_items i
  left join agg a on a.work_item_id = i.id
  where p_status is null or i.status = p_status
  order by
    case i.status when 'active' then 0 when 'done' then 1 else 2 end,
    i.created_at desc;
$$;

grant select on public.metal_product_catalog to anon, authenticated, service_role;
grant insert, update on public.metal_product_catalog to authenticated, service_role;
grant select on public.metal_work_items to anon, authenticated, service_role;
grant insert, update on public.metal_work_items to authenticated, service_role;
grant select on public.metal_stage_events to anon, authenticated, service_role;
grant insert on public.metal_stage_events to authenticated, service_role;
grant usage, select on sequence public.metal_work_items_id_seq to authenticated, service_role;
grant usage, select on sequence public.metal_stage_events_id_seq to authenticated, service_role;

grant execute on function public.web_list_metal_catalog(boolean) to anon, authenticated, service_role;
grant execute on function public.web_upsert_metal_catalog_item(text, text, boolean) to anon, authenticated, service_role;
grant execute on function public.web_create_metal_work_item(text, text, text, numeric) to anon, authenticated, service_role;
grant execute on function public.web_transition_metal_stage(bigint, text) to anon, authenticated, service_role;
grant execute on function public.web_list_metal_work_items(text) to anon, authenticated, service_role;
