-- Seed furniture->metal mapping from legacy excel-derived SQL

insert into public.furniture_metal_map (furniture_article, metal_article, metal_name, qty_per_unit, is_active)
values
  ('GXctbLoftVo', 'GXctbLoftB', 'Ноги для журнального стола Лофт', 1, true),
  ('GXctbLoftOs', 'GXctbLoftB', 'Ноги для журнального стола Лофт', 1, true),
  ('GXctbLoftUt', 'GXctbLoftB', 'Ноги для журнального стола Лофт', 1, true),
  ('GXktStadioSLKB', 'GXtbStadioB', 'Ноги для Stadio. Черные. Компл.', 1, true),
  ('GXktAvellaBC001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaOB001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaVO001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaGB001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaOK001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaHDO001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaPGS001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaCARM001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaSS001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXktAvellaTA001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXkitchtableDoWBC001s', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoWVOs', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoWOSs', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoWHDOs', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoWCMBs', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoWUTs', 'GXtbDonini730W', 'Ноги для Donini 75. Белые. Компл', 1, true),
  ('GXkitchtableDoBC001s', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoWWWs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoOB001s', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoVOs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoMOs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoHDOs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoDBC001s', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoINTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoPGS001s', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoKTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoCMs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoSLTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoTSAs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXkitchtableDoWBC001', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoWVO', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoWOS', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoWHDO', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoWCMB', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoWUT', 'GXtbDonini784W', 'Ноги для Donini 80. Белые. Компл', 1, true),
  ('GXkitchtableDoBC001', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoWWW', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoOB001', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoVO', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoMO', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoHDO', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoDBC001', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoINT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoPGS001', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoKT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoCM', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoSLT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXkitchtableDoTSA', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGBTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGGEs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGVOs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGODs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGOKs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGOSs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGPGSs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGCARMs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGUTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGAADs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktDoGBT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGGE', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGVO', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGOD', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGOK', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGOS', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGPGS', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGCARM', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGUT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktDoGAAD', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoVOs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoBTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoOks', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoOSs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoPGSs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoCARMs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoUTs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoAADs', 'GXtbDonini730B', 'Ноги для Donini 75. Черные. Компл', 1, true),
  ('GXktRDoBT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoVO', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoOk', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoOS', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoPGS', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoCARM', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoUT', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktRDoAAD', 'GXtbDonini784B', 'Ноги для Donini 80. Черные. Компл', 1, true),
  ('GXktPinoBBt', 'GxtbPinoB', 'Ноги для Pino. Черные. Компл', 1, true),
  ('GXktPinoBVo', 'GxtbPinoB', 'Ноги для Pino. Черные. Компл', 1, true),
  ('GXktPinoBOs', 'GxtbPinoB', 'Ноги для Pino. Черные. Компл', 1, true),
  ('GXktPinoBUt', 'GxtbPinoB', 'Ноги для Pino. Черные. Компл', 1, true),
  ('GXktPinoBAAD', 'GxtbPinoB', 'Ноги для Pino. Черные. Компл', 1, true),
  ('GXktPinoXBBt', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXktPinoXBVo', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXktPinoXBOs', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXktPinoXBUt', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXktPinoXBAAD', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXktPinoSXLKB', 'GxtbPinoXB', 'Ноги для Pino X. Черные. Компл', 1, true),
  ('GXodKlassikoWCP', 'GXtbClassicoW', 'Ноги для Classico. Белые. Компл', 1, true),
  ('GXodKlassikoGMB', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoOB', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoDBC', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoWWW', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoCP', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoCMT', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassikoAAD', 'GXtbClassicoB', 'Ноги для Classico. Черные. Компл', 1, true),
  ('GXodKlassiko+VO', 'GXtbClassico+B', 'Ноги для Classico+. Черные. Компл', 1, true),
  ('GXodKlassiko+ONB', 'GXtbClassico+B', 'Ноги для Classico+. Черные. Компл', 1, true),
  ('GXodKlassiko+OS', 'GXtbClassico+B', 'Ноги для Classico+. Черные. Компл', 1, true),
  ('GXodKlassiko+UT', 'GXtbClassico+B', 'Ноги для Classico+. Черные. Компл', 1, true),
  ('GXodPremWBC', 'GXtbPremierW', 'Ноги для Premier. Белые. Компл', 1, true),
  ('GXodPremWBKO', 'GXtbPremierW', 'Ноги для Premier. Белые. Компл', 1, true),
  ('GXodPremWDHO', 'GXtbPremierW', 'Ноги для Premier. Белые. Компл', 1, true),
  ('GXodPremWSS', 'GXtbPremierW', 'Ноги для Premier. Белые. Компл', 1, true),
  ('GXodPremWTA', 'GXtbPremierW', 'Ноги для Premier. Белые. Компл', 1, true),
  ('GXodPremBC', 'GXtbPremierB', 'Ноги для Premier. Черные. Компл', 1, true),
  ('GXodPremBKO', 'GXtbPremierB', 'Ноги для Premier. Черные. Компл', 1, true),
  ('GXodPremDHO', 'GXtbPremierB', 'Ноги для Premier. Черные. Компл', 1, true),
  ('GXodPremSS', 'GXtbPremierB', 'Ноги для Premier. Черные. Компл', 1, true),
  ('GXodPremTA', 'GXtbPremierB', 'Ноги для Premier. Черные. Компл', 1, true),
  ('GXofficedeskBC001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskOB001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskVO001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskGB001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskOK001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskHDO001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskPGS001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskCARM001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskSS001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskTA001L', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskAL001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskBC001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskOB001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskVO001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskGB001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskHDO001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskSS001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXofficedeskTA001', 'GXtbAvellaB', 'Ноги для Avella. Черные. Компл.', 1, true),
  ('GXodCremonaBC', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXodCremonaOB', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXodCremonaVO', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXodCremonaHDO', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXodCremonaCP', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXodCremonaUt', 'GXtbCremonaB', 'Ноги для Cremona. Черные. Компл', 1, true),
  ('GXofficedesk90+BC', 'GXtbSolitoB1', 'Нога для Solito. Черная. 1 шт.', 1, true),
  ('GXofficedesk90+SKT', 'GXtbSolitoB1', 'Нога для Solito. Черная. 1 шт.', 1, true),
  ('GXofficedesk90+CP', 'GXtbSolitoB1', 'Нога для Solito. Черная. 1 шт.', 1, true),
  ('GXofficedeskSWBPW', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWWWW', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWGMB', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWNAO001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWOB001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWDBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWKT', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWCP001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSWTSA', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWOB001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWCP001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWBPW', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWWWW', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWGMB', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWNAO001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWDBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWKT', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk135SWTSA', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk90SWBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk90SWOB001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk90SWDBC001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedesk90SWCP001', 'GXtbSolitoW', 'Ноги для Solito. Белые. Компл.', 1, true),
  ('GXofficedeskSBPW', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSWWW', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSGMB', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSNAO001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSOB001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSDBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSKT', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSSC', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSCP001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSTSA', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskSCMT', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SOB001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SCP001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SBPW', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SWWW', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SGMB', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SNAO001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SDBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SKT', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135SSC', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk135STSA', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SAL001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SNAO001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SOB001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SDBC001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SKT', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedesk90SCP001', 'GXtbSolitoB', 'Ноги для Solito. Черные. Компл.', 1, true),
  ('GXofficedeskS2MA', 'GXtbSolito2B', 'Ноги для Solito2. Черные. Компл.', 1, true),
  ('GXofficedeskS2MU', 'GXtbSolito2B', 'Ноги для Solito2. Черные. Компл.', 1, true),
  ('GXofficedeskS2SU', 'GXtbSolito2B', 'Ноги для Solito2. Черные. Компл.', 1, true),
  ('GXofficedeskS2CH', 'GXtbSolito2B', 'Ноги для Solito2. Черные. Компл.', 1, true),
  ('GXodStabile115x65BC', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile115x65OB', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile115x65CP', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65AL', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65BC', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65OB', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65VO', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65CO', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65INT', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodStabile135x65CP', 'GXtbStabileB', 'Ноги для Stabile. Черные. Компл', 1, true),
  ('GXodAncona90KNAO', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodCB_OsGphYs', 'GXodCB', 'Ноги для стола Color block без тумбы', 1, true),
  ('GXodCB_OsGphY', 'GXodCBt', 'Ноги для стола Color block  с тумбой', 1, true),
  ('GXktAncona2HDO', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXktAncona2PGS', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXktAncona2TRR', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXktAncona2TA', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK115AL', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona115AL', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK115OB', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona115OB', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK115CP', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona115CP', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK135BC', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona135BC', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK135OB', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona135OB', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAnconaK135DBC', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona90KAL', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXodAncona90NAO', 'GXcornersAnconaB', 'Уголки для Ancona металлические, черные. Комплект', 1, true),
  ('GXcstCB_OsGphYs', 'GXcstCB', 'Ноги для комода Color block', 1, true),
  ('GXshrckS1IntEr', 'GXshrckSienaB', 'Ноги для обувницы Siena. Черные + Ручка Л-образная 296 мм цвет чёрный', 1, true),
  ('GXshrckS1IvEr', 'GXshrckSienaB', 'Ноги для обувницы Siena. Черные + Ручка Л-образная 296 мм цвет чёрный', 1, true),
  ('GXshrckS1UtGph', 'GXshrckSienaB', 'Ноги для обувницы Siena. Черные + Ручка Л-образная 296 мм цвет чёрный', 1, true),
  ('GXssShShelf400WOS', 'GXssBrackets+Sh400HW', 'Кронштейны системы хранения - 2 шт, Упор обувницы 400 - 1 шт, уголок тупой - 1 шт, белые', 1, true),
  ('GXssShShelf400BVO', 'GXssBrackets+Sh400HB', 'Кронштейны системы хранения - 2 шт, Упор обувницы 400 - 1 шт, уголок тупой - 1 шт, черные', 1, true),
  ('GXssShShelf600WOS', 'GXssBrackets+Sh600HW', 'Кронштейны системы хранения - 2 шт, Упор обувницы 600 - 1 шт, уголок тупой - 1 шт, белые', 1, true),
  ('GXssShShelf600BVO', 'GXssBrackets+Sh600HB', 'Кронштейны системы хранения - 2 шт, Упор обувницы 600 - 1 шт,  уголок тупой - 1 шт, черные', 1, true),
  ('GXssShShelf900WOS', 'GXssBrackets+Sh900HW', 'Кронштейны системы хранения - 2 шт, Упор обувницы 900 - 1 шт, уголок тупой - 1 шт, белые', 1, true),
  ('GXssShShelf900BVO', 'GXssBrackets+Sh900HB', 'Кронштейны системы хранения - 2 шт, Упор обувницы 900 - 1 шт, уголок тупой - 1 шт, черные', 1, true),
  ('GXssShelf400WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssShelf400BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelf44-400BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelf600WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssShelf600BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelf44-600BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelf900WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssShelf900BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelf44-900BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssShelfCo400BVO', 'GXssBrackets+HCoB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 2 шт, черные', 1, true),
  ('GXssShelfCo600BVO', 'GXssBrackets+HCoB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 2 шт, черные', 1, true),
  ('GXssShelfCo900BVO', 'GXssBrackets+HCoB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 2 шт, черные', 1, true),
  ('GXbstLoftVo', 'GXbstLoftB', 'Ноги для прикроватной тумбы Лофт', 1, true),
  ('GXbstLoftOs', 'GXbstLoftB', 'Ноги для прикроватной тумбы Лофт', 1, true),
  ('GXbstLoftUt', 'GXbstLoftB', 'Ноги для прикроватной тумбы Лофт', 1, true),
  ('GXss2-400-600hWOS', 'GXss2-400-600hW', 'Комплект системы хранения, 3 опоры, 16 кронштейнов, 2 штанги вешалки, 1 уголок обувницы. Белый', 1, true),
  ('GXss44-2-400-600hBVO', 'GXss2-400-600hB', 'Комплект системы хранения, 3 опоры, 16 кронштейнов, 2 штанги вешалки, 1 уголок обувницы. Черный', 1, true),
  ('GXss2-400-600hBVO', 'GXss2-400-600hB', 'Комплект системы хранения, 3 опоры, 16 кронштейнов, 2 штанги вешалки, 1 уголок обувницы. Черный', 1, true),
  ('GXss1-600WOS', 'GXss1W', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Белый', 1, true),
  ('GXss1-600BVO', 'GXss1B', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Черный', 1, true),
  ('GXss44-1-600BVO', 'GXss1B', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Черный', 1, true),
  ('GXss1-900hWOS', 'GXss1hW', 'Комплект системы хранения, 2 опоры, 6 кронштейнов, 1 штанга вешалки, 1 уголок обувницы. Белый', 1, true),
  ('GXss44-1-900hBVO', 'GXss1hB', 'Комплект системы хранения, 2 опоры, 6 кронштейнов, 1 штанга вешалки, 1 уголок обувницы. Черный', 1, true),
  ('GXss1-900hBVO', 'GXss1hB', 'Комплект системы хранения, 2 опоры, 6 кронштейнов, 1 штанга вешалки, 1 уголок обувницы. Черный', 1, true),
  ('GXss1-900WOS', 'GXss1W', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Белый', 1, true),
  ('GXss44-1-900BVO', 'GXss1B', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Черный', 1, true),
  ('GXss1-900BVO', 'GXss1B', 'Комплект системы хранения с 2 опорами кронштейнами, 10 кронштейнов. Черный', 1, true),
  ('GXss2-900hWOS', 'GXss2hW', 'Комплект системы хранения, 3 опоры, 12 кронштейнов, 2 штанги вешалки, 2 уголка обувницы. Белый', 1, true),
  ('GXss44-2-900hBVO', 'GXss2hB', 'Комплект системы хранения, 3 опоры, 12 кронштейнов, 2 штанги вешалки, 2 уголка обувницы. Черный', 1, true),
  ('GXss2-900hBVO', 'GXss2hB', 'Комплект системы хранения, 3 опоры, 12 кронштейнов, 2 штанги вешалки, 2 уголка обувницы. Черный', 1, true),
  ('GXrckLoftVo', 'GXrckLoftB', 'Ноги для сталлажа Лофт. Черные', 1, true),
  ('GXrckLoftOs', 'GXrckLoftB', 'Ноги для сталлажа Лофт. Черные', 1, true),
  ('GXrckLoftUt', 'GXrckLoftB', 'Ноги для сталлажа Лофт. Черные', 1, true),
  ('GXSO4sWaGMB', 'GXframeSO4sW', 'Рама для стеллажа Solito3. Белые. Компл.', 1, true),
  ('GXSO4sWaOB', 'GXframeSO4sW', 'Рама для стеллажа Solito3. Белые. Компл.', 1, true),
  ('GXSO4sWaDBC', 'GXframeSO4sW', 'Рама для стеллажа Solito3. Белые. Компл.', 1, true),
  ('GXSO4sWaCP', 'GXframeSO4sW', 'Рама для стеллажа Solito3. Белые. Компл.', 1, true),
  ('GXSO4sWaTSA', 'GXframeSO4sW', 'Рама для стеллажа Solito3. Белые. Компл.', 1, true),
  ('GXSO4sDBC', 'GXframeSO4sB', 'Рама для стеллажа Solito3. Черные. Компл.', 1, true),
  ('GXSO4saGMB', 'GXframeSO4sB', 'Рама для стеллажа Solito3. Черные. Компл.', 1, true),
  ('GXSO4saKT', 'GXframeSO4sB', 'Рама для стеллажа Solito3. Черные. Компл.', 1, true),
  ('GXSO4saTSA', 'GXframeSO4sB', 'Рама для стеллажа Solito3. Черные. Компл.', 1, true),
  ('GXSO4sCP', 'GXframeSO4sB', 'Рама для стеллажа Solito3. Черные. Компл.', 1, true),
  ('GXrckCB_OsGphYs', 'GXrckCB', 'Ноги для сталлажа Color block', 1, true),
  ('GXtvsLoftGVo', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftGMo', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftGOs', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftGInt', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftGTsa', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftGUt', 'GXtvsbLoftB150', 'Ноги для тумбы под ТВ Лофт 150', 1, true),
  ('GXtvsLoftXGVo', 'GXtvsbLoftB180', 'Ноги для тумбы под ТВ Лофт 180', 1, true),
  ('GXtvsLoftXGOs', 'GXtvsbLoftB180', 'Ноги для тумбы под ТВ Лофт 180', 1, true),
  ('GXtvsLoftXGUt', 'GXtvsbLoftB180', 'Ноги для тумбы под ТВ Лофт 180', 1, true),
  ('GXtvsLoftBt', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftVo', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftOk', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftMo', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftOs', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftInt', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftTsa', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftUt', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsLoftAAD', 'GXtvsbLoftB', 'Ноги для тумбы под ТВ Лофт', 1, true),
  ('GXtvsCB_OsGphYs', 'GXtvsCB', 'Ноги для тумбы под ТВ Color block', 1, true),
  ('GXtvsModS3_Ok', 'GXtvsbModS3B', 'Ноги для тумбы Modula, 3 секции, черные', 1, true),
  ('GXtvsModS3_Kl', 'GXtvsbModS3B', 'Ноги для тумбы Modula, 3 секции, черные', 1, true),
  ('GXtvsModS3_Ut', 'GXtvsbModS3B', 'Ноги для тумбы Modula, 3 секции, черные', 1, true),
  ('GXtvsModS4_Ok', 'GXtvsbModS4B', 'Ноги для тумбы Modula, 4 секции, черные', 1, true),
  ('GXtvsModS4_Kl', 'GXtvsbModS4B', 'Ноги для тумбы Modula, 4 секции, черные', 1, true),
  ('GXtvsModS4_Ut', 'GXtvsbModS4B', 'Ноги для тумбы Modula, 4 секции, черные', 1, true),
  ('GXtvsS1IntEr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GXtvsS1IvEr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GXtvsS1UtGph', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2_150VoBr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2_150IntGr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2_150UtGr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2VoBr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2IntGr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS2UtGr', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GXtvsS3IntGeoW', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GXtvsS3BSkyGeoW', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GxtvsS3UtGeoW', 'GXtvsbSienaB', 'Ноги для тумбы под ТВ Siena', 1, true),
  ('GXtvsVel160OsSi', 'GXtvsbVel160B', 'Ноги для тумбы Valora 1600, черные', 1, true),
  ('GXtvsVel160ErPSa', 'GXtvsbVel160B', 'Ноги для тумбы Valora 1600, черные', 1, true),
  ('GXtvsVel160UtOr', 'GXtvsbVel160B', 'Ноги для тумбы Valora 1600, черные', 1, true),
  ('GXssCab34-1-600WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssCab34-1-600BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssCab34-2-600WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssCab34-2-600BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXssCab34-3-600WOS', 'GXssBrackets+HW', 'Кронштейны системы хранения, белые - 2 шт, уголок прямой - 1 шт, белые', 1, true),
  ('GXssCab34-3-600BVO', 'GXssBrackets+HB', 'Кронштейны системы хранения, черные - 2 шт, уголок прямой - 1 шт, черные', 1, true),
  ('GXtbox560FBkBk', 'GXtboxSideBk', 'Боковые планки Ящика подстольного. Черные', 1, true),
  ('GXtbox760FBkBk', 'GXtboxSideBk', 'Боковые планки Ящика подстольного. Черные', 1, true)
on conflict (furniture_article, metal_article) do update
set metal_name = excluded.metal_name,
    qty_per_unit = excluded.qty_per_unit,
    is_active = excluded.is_active,
    updated_at = now();

insert into public.metal_components_stock (metal_article, metal_name, qty_available, qty_reserved)
select m.metal_article,
       max(coalesce(nullif(trim(m.metal_name), ''), m.metal_article)) as metal_name,
       0 as qty_available,
       0 as qty_reserved
from public.furniture_metal_map m
group by m.metal_article
on conflict (metal_article) do update
set metal_name = excluded.metal_name;
