-- Generated from Соответствия.xlsx; re-run: python migration/scripts/gen_item_article_catalog_sql.py
begin;
insert into public.item_article_map (article, item_name, source, section_name, table_color, sort_order)
values
  ('GXodStabile135x65CP', 'Stabile. 1350х650. Сосна Касцина', 'xlsx_catalog', 'Stabile', 'Сосна касцина', 10),
  ('GXodStabile135x65INT', 'Stabile. 1350х650. Интра', 'xlsx_catalog', 'Stabile', 'Интра', 20),
  ('GXodStabile135x65CO', 'Stabile. 1350х650. Дуб Кальяри', 'xlsx_catalog', 'Stabile', 'Дуб кальяри', 30),
  ('GXodStabile135x65VO', 'Stabile. 1350х650. Дуб Вотан', 'xlsx_catalog', 'Stabile', 'Дуб вотан', 40),
  ('GXodStabile135x65OB', 'Stabile. 1350х650. Дуб Бардолино натуральный', 'xlsx_catalog', 'Stabile', 'Бардолино', 50),
  ('GXodStabile135x65BC', 'Stabile. 1350х650. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Stabile', 'Бетон чикаго', 60),
  -- 1150x650 variants removed by request.
  ('GXofficedeskS2SU', 'Solito2. Серия 1156. Солнечный', 'xlsx_catalog', 'Solito2', 'Солнечный', 10),
  ('GXofficedeskS2MU', 'Solito2. Серия 1156. Муза', 'xlsx_catalog', 'Solito2', 'Муза', 20),
  ('GXofficedeskS2MA', 'Solito2. Серия 1156. Маренго', 'xlsx_catalog', 'Solito2', 'Маренго', 30),
  ('GXofficedesk135STSA', 'Solito. Серия 1350. Трансильвания', 'xlsx_catalog', 'Solito 1350 черный', 'Трансильвания', 10),
  ('GXofficedesk135SKT', 'Solito. Серия 1350. Кейптаун', 'xlsx_catalog', 'Solito 1350 черный', 'Кейптаун', 20),
  ('GXofficedesk135SDBC001', 'Solito. Серия 1350. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Solito 1350 черный', 'Дуб чарльзтон', 30),
  ('GXofficedesk135SWWW', 'Solito. Серия 1350. Выбеленное дерево', 'xlsx_catalog', 'Solito 1350 черный', 'Выбеленное дерево', 40),
  ('GXofficedesk135SCP001', 'Solito. Серия 1350 Сосна Касцина', 'xlsx_catalog', 'Solito 1350 черный', 'Сосна касцина', 50),
  ('GXofficedesk135SOB001', 'Solito. Серия 1350 Дуб Бардолино натуральный', 'xlsx_catalog', 'Solito 1350 черный', 'Бардолино', 60),
  ('GXofficedesk135SBC001', 'Solito. Серия 1350 Бетон Чикаго светло-серый', 'xlsx_catalog', 'Solito 1350 черный', 'Бетон чикаго', 70),
  ('GXofficedeskSTSA', 'Solito. Серия 1150. Трансильвания', 'xlsx_catalog', 'Solito 1150', 'Трансильвания', 10),
  ('GXofficedeskSCP001', 'Solito. Серия 1150. Сосна Касцина', 'xlsx_catalog', 'Solito 1150', 'Сосна касцина', 20),
  ('GXofficedeskSKT', 'Solito. Серия 1150. Кейптаун', 'xlsx_catalog', 'Solito 1150', 'Кейптаун', 30),
  ('GXofficedeskSDBC001', 'Solito. Серия 1150. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Solito 1150', 'Дуб чарльзтон', 40),
  ('GXofficedeskSOB001', 'Solito. Серия 1150. Дуб Бардолино натуральный', 'xlsx_catalog', 'Solito 1150', 'Бардолино', 50),
  ('GXofficedeskSWWW', 'Solito. Серия 1150. Выбеленное дерево', 'xlsx_catalog', 'Solito 1150', 'Выбеленное дерево', 60),
  ('GXofficedeskSBC001', 'Solito. Серия 1150. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Solito 1150', 'Бетон чикаго', 70),
  ('GXofficedesk135SWTSA', 'Solito, белый. Серия 1350. Трансильвания', 'xlsx_catalog', 'Solito 1350 белый', 'Трансильвания', 10),
  ('GXofficedesk135SWKT', 'Solito, белый. Серия 1350. Кейптаун', 'xlsx_catalog', 'Solito 1350 белый', 'Кейптаун', 20),
  ('GXofficedesk135SWDBC001', 'Solito, белый. Серия 1350. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Solito 1350 белый', 'Дуб чарльзтон', 30),
  ('GXofficedesk135SWWWW', 'Solito, белый. Серия 1350. Выбеленное дерево', 'xlsx_catalog', 'Solito 1350 белый', 'Выбеленное дерево', 40),
  ('GXofficedesk135SWCP001', 'Solito, белый. Серия 1350 Сосна Касцина', 'xlsx_catalog', 'Solito 1350 белый', 'Сосна касцина', 50),
  ('GXofficedesk135SWOB001', 'Solito, белый. Серия 1350 Дуб Бардолино натуральный', 'xlsx_catalog', 'Solito 1350 белый', 'Бардолино', 60),
  ('GXofficedesk135SWBC001', 'Solito, белый. Серия 1350 Бетон Чикаго светло-серый', 'xlsx_catalog', 'Solito 1350 белый', 'Бетон чикаго', 70),
  ('GXofficedeskSWTSA', 'Solito, белый. Серия 1150. Трансильвания', 'xlsx_catalog', 'Solito 1150', 'Трансильвания', 10),
  ('GXofficedeskSWCP001', 'Solito, белый. Серия 1150. Сосна Касцина', 'xlsx_catalog', 'Solito 1150', 'Сосна касцина', 20),
  ('GXofficedeskSWKT', 'Solito, белый. Серия 1150. Кейптаун', 'xlsx_catalog', 'Solito 1150', 'Кейптаун', 30),
  ('GXofficedeskSWDBC001', 'Solito, белый. Серия 1150. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Solito 1150', 'Дуб чарльзтон', 40),
  ('GXofficedeskSWOB001', 'Solito, белый. Серия 1150. Дуб Бардолино натуральный', 'xlsx_catalog', 'Solito 1150', 'Бардолино', 50),
  ('GXofficedeskSWWWW', 'Solito, белый. Серия 1150. Выбеленное дерево', 'xlsx_catalog', 'Solito 1150', 'Выбеленное дерево', 60),
  ('GXofficedeskSWBC001', 'Solito, белый. Серия 1150. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Solito 1150', 'Бетон чикаго', 70),
  ('GXodCremonaUt', 'Cremona. 1350х700. Юта', 'xlsx_catalog', 'Cremona', 'Юта', 10),
  ('GXodCremonaCP', 'Cremona. 1350х700. Сосна Касцина', 'xlsx_catalog', 'Cremona', 'Сосна касцина', 20),
  ('GXodCremonaHDO', 'Cremona. 1350х700. Дуб Хантон темный', 'xlsx_catalog', 'Cremona', 'Дуб хантон', 30),
  ('GXodCremonaVO', 'Cremona. 1350х700. Дуб Вотан', 'xlsx_catalog', 'Cremona', 'Дуб вотан', 40),
  ('GXodCremonaOB', 'Cremona. 1350х700. Дуб Бардолино натуральный', 'xlsx_catalog', 'Cremona', 'Бардолино', 50),
  ('GXodCremonaBC', 'Cremona. 1350х700. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Cremona', 'Бетон чикаго', 60),
  ('GXofficedeskTA001', 'Avella. Ясень Тронхейм', 'xlsx_catalog', 'Avella', 'Ясень тронхейм', 10),
  ('GXofficedeskSS001', 'Avella. Сланец Скиваро', 'xlsx_catalog', 'Avella', 'Сланец Скиваро', 20),
  ('GXofficedeskHDO001', 'Avella. Дуб Хантон темный', 'xlsx_catalog', 'Avella', 'Дуб хантон', 30),
  ('GXofficedeskGB001', 'Avella. Дуб Галифакс олово', 'xlsx_catalog', 'Avella', 'Дуб галифакс олово', 40),
  ('GXofficedeskVO001', 'Avella. Дуб Вотан', 'xlsx_catalog', 'Avella', 'Дуб вотан', 50),
  ('GXofficedeskOB001', 'Avella. Дуб Бардолино натуральный', 'xlsx_catalog', 'Avella', 'Бардолино', 60),
  ('GXofficedeskBC001', 'Avella. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Avella', 'Бетон чикаго', 70),
  ('GXofficedeskTA001L', 'Avella lite. Ясень Тронхейм', 'xlsx_catalog', 'Avella lite', 'Ясень тронхейм', 10),
  ('GXofficedeskSS001L', 'Avella lite. Сланец Скиваро', 'xlsx_catalog', 'Avella lite', 'Сланец Скиваро', 20),
  ('GXofficedeskPGS001L', 'Avella lite. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Avella lite', 'Камень пьетра гриджиа', 30),
  ('GXofficedeskHDO001L', 'Avella lite. Дуб Хантон темный', 'xlsx_catalog', 'Avella lite', 'Дуб хантон', 40),
  ('GXofficedeskOK001L', 'Avella lite. Дуб Коми', 'xlsx_catalog', 'Avella lite', 'Дуб коми', 50),
  ('GXofficedeskGB001L', 'Avella lite. Дуб Галифакс олово', 'xlsx_catalog', 'Avella lite', 'Дуб галифакс олово', 60),
  ('GXofficedeskVO001L', 'Avella lite. Дуб Вотан', 'xlsx_catalog', 'Avella lite', 'Дуб вотан', 70),
  ('GXofficedeskOB001L', 'Avella lite. Дуб Бардолино натуральный', 'xlsx_catalog', 'Avella lite', 'Бардолино', 80),
  ('GXofficedeskBC001L', 'Avella lite. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Avella lite', 'Бетон чикаго', 90),
  ('GXodPremTA', 'Премьер. Черный. Ясень Тронхейм', 'xlsx_catalog', 'Премьер черный', 'Ясень тронхейм 25', 10),
  ('GXodPremSS', 'Премьер. Черный. Сланец Скиваро', 'xlsx_catalog', 'Премьер черный', 'Сланец Скиваро 25', 20),
  ('GXodPremDHO', 'Премьер. Черный. Дуб Хантон тёмный', 'xlsx_catalog', 'Премьер черный', 'Дуб хантон 25', 30),
  ('GXodPremBKO', 'Премьер. Черный. Дуб Канзас коричневый', 'xlsx_catalog', 'Премьер черный', 'дуб канзас 25', 40),
  ('GXodPremBC', 'Премьер. Черный. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Премьер черный', 'Бетон чикаго 25', 50),
  ('GXodPremWTA', 'Премьер. Белый. Ясень Тронхейм', 'xlsx_catalog', 'Премьер белый', 'Ясень тронхейм 25', 10),
  ('GXodPremWSS', 'Премьер. Белый. Сланец Скиваро', 'xlsx_catalog', 'Премьер белый', 'Сланец Скиваро 25', 20),
  ('GXodPremWDHO', 'Премьер. Белый. Дуб Хантон тёмный', 'xlsx_catalog', 'Премьер белый', 'Дуб хантон 25', 30),
  ('GXodPremWBKO', 'Премьер. Белый. Дуб Канзас коричневый', 'xlsx_catalog', 'Премьер белый', 'дуб канзас 25', 40),
  ('GXodPremWBC', 'Премьер. Белый. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Премьер белый', 'Бетон чикаго 25', 50),
  ('GXodKlassiko+UT', 'Классико+. Юта', 'xlsx_catalog', 'Классико +', 'Юта', 10),
  ('GXodKlassiko+OS', 'Классико+. Дуб сонома', 'xlsx_catalog', 'Классико +', 'Бардолино', 20),
  ('GXodKlassiko+VO', 'Классико+. Дуб вотан', 'xlsx_catalog', 'Классико +', 'Дуб вотан', 30),
  ('GXodKlassikoAAD', 'Классико. Ясень Анкор Темный', 'xlsx_catalog', 'Классико', 'Ясень анкор', 10),
  ('GXodKlassikoCMT', 'Классико. Цемент', 'xlsx_catalog', 'Классико', 'Цемент', 20),
  ('GXodKlassikoCP', 'Классико. Сосна Касцина', 'xlsx_catalog', 'Классико', 'Сосна касцина', 30),
  ('GXodKlassikoDBC', 'Классико. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Классико', 'Дуб чарльзтон', 40),
  ('GXodKlassikoOB', 'Классико. Дуб Бардолино натуральный', 'xlsx_catalog', 'Классико', 'Бардолино', 50),
  ('GXodKlassikoWCP', 'Классико, Белый. Сосна Касцина', 'xlsx_catalog', 'Классико', 'Сосна касцина', 60),
  ('GXktRDoAAD', 'Donini R 806 мм. Ясень Анкор Темный', 'xlsx_catalog', 'Donini R 806', 'Ясень анкор', 10),
  ('GXktRDoUT', 'Donini R 806 мм. Юта', 'xlsx_catalog', 'Donini R 806', 'Юта', 20),
  ('GXktRDoPGS', 'Donini R 806 мм. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Donini R 806', 'Камень пьетра гриджиа', 30),
  ('GXktRDoOS', 'Donini R 806 мм. Дуб Сонома', 'xlsx_catalog', 'Donini R 806', 'Бардолино', 40),
  ('GXktRDoOk', 'Donini R 806 мм. Дуб Коми', 'xlsx_catalog', 'Donini R 806', 'Дуб коми', 50),
  ('GXktRDoVO', 'Donini R 806 мм. Дуб Вотан', 'xlsx_catalog', 'Donini R 806', 'Дуб вотан', 60),
  ('GXktRDoBT', 'Donini R 806 мм. Бетон', 'xlsx_catalog', 'Donini R 806', 'Бетон', 70),
  ('GXktRDoAADs', 'Donini R 750 мм. Ясень Анкор Темный', 'xlsx_catalog', 'Donini R 750', 'Ясень анкор', 10),
  ('GXktRDoUTs', 'Donini R 750 мм. Юта', 'xlsx_catalog', 'Donini R 750', 'Юта', 20),
  ('GXktRDoPGSs', 'Donini R 750 мм. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Donini R 750', 'Камень пьетра гриджиа', 30),
  ('GXktRDoOSs', 'Donini R 750 мм. Дуб Сонома', 'xlsx_catalog', 'Donini R 750', 'Бардолино', 40),
  ('GXktRDoOks', 'Donini R 750 мм. Дуб Коми', 'xlsx_catalog', 'Donini R 750', 'Дуб коми', 50),
  ('GXktRDoBTs', 'Donini R 750 мм. Бетон', 'xlsx_catalog', 'Donini R 750', 'Бетон', 60),
  ('GXktRDoVOs', 'Donini R 750 мм. Дуб Вотан', 'xlsx_catalog', 'Donini R 750', 'Дуб вотан', 70),
  ('GXktDoGAAD', 'Donini Grande 806 мм. Ясень Анкор Темный', 'xlsx_catalog', 'Donini Grande 806', 'Ясень анкор', 10),
  ('GXktDoGUT', 'Donini Grande 806 мм. Юта', 'xlsx_catalog', 'Donini Grande 806', 'Юта', 20),
  ('GXktDoGPGS', 'Donini Grande 806 мм. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Donini Grande 806', 'Камень пьетра гриджиа', 30),
  ('GXktDoGOS', 'Donini Grande 806 мм. Дуб Сонома', 'xlsx_catalog', 'Donini Grande 806', 'Бардолино', 40),
  ('GXktDoGOK', 'Donini Grande 806 мм. Дуб Коми', 'xlsx_catalog', 'Donini Grande 806', 'Дуб коми', 50),
  ('GXktDoGOD', 'Donini Grande 806 мм. Дуб Делано темный', 'xlsx_catalog', 'Donini Grande 806', 'Дуб делано', 60),
  ('GXktDoGVO', 'Donini Grande 806 мм. Дуб Вотан', 'xlsx_catalog', 'Donini Grande 806', 'Дуб вотан', 70),
  ('GXktDoGGE', 'Donini Grande 806 мм. Герион', 'xlsx_catalog', 'Donini Grande 806', 'Герион', 80),
  ('GXktDoGBT', 'Donini Grande 806 мм. Бетон', 'xlsx_catalog', 'Donini Grande 806', 'Бетон', 90),
  ('GXktDoGAADs', 'Donini Grande 750 мм. Ясень Анкор Темный', 'xlsx_catalog', 'Donini Grande 750', 'Ясень анкор', 10),
  ('GXktDoGUTs', 'Donini Grande 750 мм. Юта', 'xlsx_catalog', 'Donini Grande 750', 'Юта', 20),
  ('GXktDoGPGSs', 'Donini Grande 750 мм. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Donini Grande 750', 'Камень пьетра гриджиа', 30),
  ('GXktDoGOSs', 'Donini Grande 750 мм. Дуб Сонома', 'xlsx_catalog', 'Donini Grande 750', 'Бардолино', 40),
  ('GXktDoGOKs', 'Donini Grande 750 мм. Дуб Коми', 'xlsx_catalog', 'Donini Grande 750', 'Дуб коми', 50),
  ('GXktDoGODs', 'Donini Grande 750 мм. Дуб Делано темный', 'xlsx_catalog', 'Donini Grande 750', 'Дуб делано', 60),
  ('GXktDoGVOs', 'Donini Grande 750 мм. Дуб Вотан', 'xlsx_catalog', 'Donini Grande 750', 'Дуб вотан', 70),
  ('GXktDoGGEs', 'Donini Grande 750 мм. Герион', 'xlsx_catalog', 'Donini Grande 750', 'Герион', 80),
  ('GXktDoGBTs', 'Donini Grande 750 мм. Бетон', 'xlsx_catalog', 'Donini Grande 750', 'Бетон', 90),
  ('GXkitchtableDoTSA', 'Donini 806 мм. Трансильвания', 'xlsx_catalog', 'Donini 806', 'Трансильвания', 10),
  ('GXkitchtableDoCM', 'Donini 806 мм. Мрамор Кристалл', 'xlsx_catalog', 'Donini 806', 'Мрамор кристал', 20),
  ('GXkitchtableDoKT', 'Donini 806 мм. Кейптаун', 'xlsx_catalog', 'Donini 806', 'Кейптаун', 30),
  ('GXkitchtableDoPGS001', 'Donini 806 мм. Камень Пьетра Гриджиа чёрный', 'xlsx_catalog', 'Donini 806', 'Камень пьетра гриджиа', 40),
  ('GXkitchtableDoINT', 'Donini 806 мм. Интра', 'xlsx_catalog', 'Donini 806', 'Интра', 50),
  ('GXkitchtableDoDBC001', 'Donini 806 мм. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Donini 806', 'Дуб чарльзтон', 60),
  ('GXkitchtableDoHDO', 'Donini 806 мм. Дуб Хантон темный', 'xlsx_catalog', 'Donini 806', 'Дуб хантон', 70),
  ('GXkitchtableDoMO', 'Donini 806 мм. Дуб Марсала', 'xlsx_catalog', 'Donini 806', 'Дуб марсала', 80),
  ('GXkitchtableDoVO', 'Donini 806 мм. Дуб Вотан', 'xlsx_catalog', 'Donini 806', 'Дуб вотан', 90),
  ('GXkitchtableDoOB001', 'Donini 806 мм. Дуб Бардолино натуральный', 'xlsx_catalog', 'Donini 806', 'Бардолино', 100),
  ('GXkitchtableDoWWW', 'Donini 806 мм. Выбеленное дерево', 'xlsx_catalog', 'Donini 806', 'Выбеленное дерево', 110),
  ('GXkitchtableDoBC001', 'Donini 806 мм. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Donini 806', 'Бетон чикаго', 120),
  ('GXkitchtableDoWUT', 'Donini 806 мм. Белые ноги. Юта', 'xlsx_catalog', 'Donini 806', 'Юта', 10),
  ('GXkitchtableDoWCMB', 'Donini 806 мм. Белые ноги. Мрамор Кристалл', 'xlsx_catalog', 'Donini 806', 'Мрамор кристал', 20),
  ('GXkitchtableDoWHDO', 'Donini 806 мм. Белые ноги. Дуб Хантон', 'xlsx_catalog', 'Donini 806', 'Дуб хантон', 30),
  ('GXkitchtableDoWOS', 'Donini 806 мм. Белые ноги. Дуб Сонома', 'xlsx_catalog', 'Donini 806', 'Бардолино', 40),
  ('GXkitchtableDoWVO', 'Donini 806 мм. Белые ноги. Дуб Вотан', 'xlsx_catalog', 'Donini 806', 'Дуб вотан', 50),
  ('GXkitchtableDoWBC001', 'Donini 806 мм. Белые ноги. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Donini 806', 'Бетон чикаго', 60),
  ('GXkitchtableDoTSAs', 'Donini 750 мм. Трансильвания', 'xlsx_catalog', 'Donini 750', 'Трансильвания', 10),
  ('GXkitchtableDoCMs', 'Donini 750 мм. Мрамор Кристалл', 'xlsx_catalog', 'Donini 750', 'Мрамор кристал', 20),
  ('GXkitchtableDoKTs', 'Donini 750 мм. Кейптаун', 'xlsx_catalog', 'Donini 750', 'Кейптаун', 30),
  ('GXkitchtableDoPGS001s', 'Donini 750 мм. Камень Пьетра Гриджиа чёрный.', 'xlsx_catalog', 'Donini 750', 'Камень пьетра гриджиа', 40),
  ('GXkitchtableDoINTs', 'Donini 750 мм. Интра', 'xlsx_catalog', 'Donini 750', 'Интра', 50),
  ('GXkitchtableDoDBC001s', 'Donini 750 мм. Дуб Чарльстон тёмно-коричневый', 'xlsx_catalog', 'Donini 750', 'Дуб чарльзтон', 60),
  ('GXkitchtableDoHDOs', 'Donini 750 мм. Дуб Хантон темный', 'xlsx_catalog', 'Donini 750', 'Дуб хантон', 70),
  ('GXkitchtableDoMOs', 'Donini 750 мм. Дуб Марсала', 'xlsx_catalog', 'Donini 750', 'Дуб марсала', 80),
  ('GXkitchtableDoVOs', 'Donini 750 мм. Дуб Вотан', 'xlsx_catalog', 'Donini 750', 'Дуб вотан', 90),
  ('GXkitchtableDoOB001s', 'Donini 750 мм. Дуб Бардолино натуральный', 'xlsx_catalog', 'Donini 750', 'Бардолино', 100),
  ('GXkitchtableDoWWWs', 'Donini 750 мм. Выбеленное дерево', 'xlsx_catalog', 'Donini 750', 'Выбеленное дерево', 110),
  ('GXkitchtableDoBC001s', 'Donini 750 мм. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Donini 750', 'Бетон чикаго', 120),
  ('GXkitchtableDoWUTs', 'Donini 750 мм. Белые ноги. Юта', 'xlsx_catalog', 'Donini 750', 'Юта', 10),
  ('GXkitchtableDoWCMBs', 'Donini 750 мм. Белые ноги. Мрамор Кристалл', 'xlsx_catalog', 'Donini 750', 'Мрамор кристал', 20),
  ('GXkitchtableDoWHDOs', 'Donini 750 мм. Белые ноги. Дуб Хантон', 'xlsx_catalog', 'Donini 750', 'Дуб хантон', 30),
  ('GXkitchtableDoWOSs', 'Donini 750 мм. Белые ноги. Дуб Сонома', 'xlsx_catalog', 'Donini 750', 'Бардолино', 40),
  ('GXkitchtableDoWVOs', 'Donini 750 мм. Белые ноги. Дуб Вотан', 'xlsx_catalog', 'Donini 750', 'Дуб вотан', 50),
  ('GXkitchtableDoWBC001s', 'Donini 750 мм. Белые ноги. Бетон Чикаго светло-серый', 'xlsx_catalog', 'Donini 750', 'Бетон чикаго', 60),
  ('GXtvsLoftAAD', 'Тумба под ТВ Лофт. Ясень Анкор темный', 'xlsx_catalog', 'ТВ Лофт', 'Ясень анкор', 10),
  ('GXtvsLoftUt', 'Тумба под ТВ Лофт. Юта', 'xlsx_catalog', 'ТВ Лофт', 'Юта', 20),
  ('GXtvsLoftTsa', 'Тумба под ТВ Лофт. Трансильвания', 'xlsx_catalog', 'ТВ Лофт', 'Трансильвания', 30),
  ('GXtvsLoftInt', 'Тумба под ТВ Лофт. Интра', 'xlsx_catalog', 'ТВ Лофт', 'Интра', 40),
  ('GXtvsLoftOs', 'Тумба под ТВ Лофт. Дуб Сонома', 'xlsx_catalog', 'ТВ Лофт', 'Бардолино', 50),
  ('GXtvsLoftMo', 'Тумба под ТВ Лофт. Дуб Марсала', 'xlsx_catalog', 'ТВ Лофт', 'Дуб марсала', 60),
  ('GXtvsLoftOk', 'Тумба под ТВ Лофт. Дуб Коми', 'xlsx_catalog', 'ТВ Лофт', 'Дуб коми', 70),
  ('GXtvsLoftVo', 'Тумба под ТВ Лофт. Дуб Вотан', 'xlsx_catalog', 'ТВ Лофт', 'Дуб вотан', 80),
  ('GXtvsLoftBt', 'Тумба под ТВ Лофт. Бетон', 'xlsx_catalog', 'ТВ Лофт', 'Бетон', 90),
  ('GXtvsLoftGUt', 'Тумба под ТВ Лофт 150. Юта', 'xlsx_catalog', 'ТВ Лофт 1500', 'Юта', 10),
  ('GXtvsLoftGTsa', 'Тумба под ТВ Лофт 150. Трансильвания', 'xlsx_catalog', 'ТВ Лофт 1500', 'Трансильвания', 20),
  ('GXtvsLoftGInt', 'Тумба под ТВ Лофт 150. Интра', 'xlsx_catalog', 'ТВ Лофт 1500', 'Интра', 30),
  ('GXtvsLoftGOs', 'Тумба под ТВ Лофт 150. Дуб Сонома', 'xlsx_catalog', 'ТВ Лофт 1500', 'Бардолино', 40),
  ('GXtvsLoftGMo', 'Тумба под ТВ Лофт 150. Дуб Марсала', 'xlsx_catalog', 'ТВ Лофт 1500', 'Дуб марсала', 50),
  ('GXtvsLoftGVo', 'Тумба под ТВ Лофт 150. Дуб Вотан', 'xlsx_catalog', 'ТВ Лофт 1500', 'Дуб вотан', 60)
on conflict (article) do update set
  item_name = excluded.item_name,
  section_name = excluded.section_name,
  table_color = excluded.table_color,
  sort_order = excluded.sort_order,
  source = excluded.source,
  updated_at = now();
commit;
