-- P1: CRM audit log foundation (who/what/when for critical operations).

create table if not exists public.crm_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id uuid null,
  actor_db_role text not null default lower(coalesce(current_setting('request.jwt.claim.role', true), '')),
  actor_crm_role text not null default lower(coalesce(public.web_effective_crm_role(), 'viewer')),
  action text not null,
  entity text not null,
  entity_id text null,
  details jsonb not null default '{}'::jsonb
);

create index if not exists idx_crm_audit_log_created_at on public.crm_audit_log (created_at desc);
create index if not exists idx_crm_audit_log_action on public.crm_audit_log (action);
create index if not exists idx_crm_audit_log_entity_entity_id on public.crm_audit_log (entity, entity_id);

alter table public.crm_audit_log enable row level security;

drop policy if exists "crm_audit_log_select_admin_only" on public.crm_audit_log;
create policy "crm_audit_log_select_admin_only"
  on public.crm_audit_log
  for select
  to authenticated
  using (public.web_effective_crm_role() = 'admin');

drop policy if exists "crm_audit_log_insert_service_role_only" on public.crm_audit_log;
create policy "crm_audit_log_insert_service_role_only"
  on public.crm_audit_log
  for insert
  to service_role
  with check (true);

grant select on public.crm_audit_log to authenticated, service_role;

create or replace function public.web_audit_log_event(
  p_action text,
  p_entity text,
  p_entity_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_action text := lower(trim(coalesce(p_action, '')));
  v_entity text := lower(trim(coalesce(p_entity, '')));
begin
  if v_action = '' or v_entity = '' then
    return;
  end if;

  insert into public.crm_audit_log(
    actor_user_id,
    actor_db_role,
    actor_crm_role,
    action,
    entity,
    entity_id,
    details
  )
  values (
    auth.uid(),
    lower(coalesce(current_setting('request.jwt.claim.role', true), '')),
    lower(coalesce(public.web_effective_crm_role(), 'viewer')),
    v_action,
    v_entity,
    nullif(trim(coalesce(p_entity_id, '')), ''),
    coalesce(p_details, '{}'::jsonb)
  );
end;
$$;

grant execute on function public.web_audit_log_event(text, text, text, jsonb) to anon, authenticated, service_role;

create or replace function public.trg_crm_audit_orders()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
begin
  if tg_op = 'DELETE' then
    perform public.web_audit_log_event(
      'delete_order',
      'orders',
      old.order_id,
      jsonb_build_object(
        'source', old.source,
        'source_row_id', old.source_row_id,
        'item', old.item
      )
    );
    return old;
  end if;

  if tg_op = 'UPDATE' then
    if coalesce(old.pilka_status, '') is distinct from coalesce(new.pilka_status, '')
       or coalesce(old.kromka_status, '') is distinct from coalesce(new.kromka_status, '')
       or coalesce(old.pras_status, '') is distinct from coalesce(new.pras_status, '')
       or coalesce(old.assembly_status, '') is distinct from coalesce(new.assembly_status, '')
       or coalesce(old.overall_status, '') is distinct from coalesce(new.overall_status, '') then
      perform public.web_audit_log_event(
        'set_stage',
        'orders',
        coalesce(new.order_id, old.order_id),
        jsonb_build_object(
          'before', jsonb_build_object(
            'pilka_status', old.pilka_status,
            'kromka_status', old.kromka_status,
            'pras_status', old.pras_status,
            'assembly_status', old.assembly_status,
            'overall_status', old.overall_status
          ),
          'after', jsonb_build_object(
            'pilka_status', new.pilka_status,
            'kromka_status', new.kromka_status,
            'pras_status', new.pras_status,
            'assembly_status', new.assembly_status,
            'overall_status', new.overall_status
          )
        )
      );
    end if;
    return new;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_crm_audit_orders on public.orders;
create trigger trg_crm_audit_orders
after update or delete on public.orders
for each row
execute function public.trg_crm_audit_orders();

create or replace function public.trg_crm_audit_materials_moves()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
begin
  if tg_op = 'INSERT'
     and new.move_type = 'expense'
     and lower(coalesce(new.source_type, '')) = 'order' then
    perform public.web_audit_log_event(
      'consume_sheets',
      'materials_moves',
      new.id::text,
      jsonb_build_object(
        'order_id', new.source_ref,
        'material', new.material,
        'qty_sheets', new.qty_sheets
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_crm_audit_materials_moves on public.materials_moves;
create trigger trg_crm_audit_materials_moves
after insert on public.materials_moves
for each row
execute function public.trg_crm_audit_materials_moves();

create or replace function public.trg_crm_audit_runtime_settings()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
begin
  if lower(coalesce(new.key, '')) = 'crm_auth_strict' then
    perform public.web_audit_log_event(
      'toggle_strict_mode',
      'crm_runtime_settings',
      new.key,
      jsonb_build_object(
        'enabled', lower(trim(coalesce(new.value_text, ''))) = 'true',
        'updated_at', new.updated_at
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_crm_audit_runtime_settings on public.crm_runtime_settings;
create trigger trg_crm_audit_runtime_settings
after insert or update on public.crm_runtime_settings
for each row
execute function public.trg_crm_audit_runtime_settings();

create or replace function public.trg_crm_audit_user_roles()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
begin
  if tg_op = 'INSERT' then
    perform public.web_audit_log_event(
      'assign_role',
      'crm_user_roles',
      new.user_id::text,
      jsonb_build_object('role', new.role, 'note', new.note)
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if coalesce(old.role, '') is distinct from coalesce(new.role, '')
       or coalesce(old.note, '') is distinct from coalesce(new.note, '') then
      perform public.web_audit_log_event(
        'assign_role',
        'crm_user_roles',
        new.user_id::text,
        jsonb_build_object(
          'before', jsonb_build_object('role', old.role, 'note', old.note),
          'after', jsonb_build_object('role', new.role, 'note', new.note)
        )
      );
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform public.web_audit_log_event(
      'remove_role',
      'crm_user_roles',
      old.user_id::text,
      jsonb_build_object('role', old.role, 'note', old.note)
    );
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_crm_audit_user_roles on public.crm_user_roles;
create trigger trg_crm_audit_user_roles
after insert or update or delete on public.crm_user_roles
for each row
execute function public.trg_crm_audit_user_roles();

create or replace function public.web_get_audit_log(
  p_limit integer default 200,
  p_offset integer default 0,
  p_action text default null
)
returns table (
  id bigint,
  created_at timestamptz,
  actor_user_id uuid,
  actor_db_role text,
  actor_crm_role text,
  action text,
  entity text,
  entity_id text,
  details jsonb
)
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 200), 1000));
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_action text := nullif(lower(trim(coalesce(p_action, ''))), '');
begin
  perform public.web_require_roles(array['admin', 'manager']);

  return query
  select
    l.id,
    l.created_at,
    l.actor_user_id,
    l.actor_db_role,
    l.actor_crm_role,
    l.action,
    l.entity,
    l.entity_id,
    l.details
  from public.crm_audit_log l
  where v_action is null or l.action = v_action
  order by l.created_at desc, l.id desc
  limit v_limit
  offset v_offset;
end;
$$;

grant execute on function public.web_get_audit_log(integer, integer, text) to authenticated, service_role;
