create table if not exists public.sheet_orders_mirror (
  id bigint generated by default as identity primary key,
  sheet_id text not null,
  sheet_gid text not null,
  sheet_row integer not null,
  source_created_at_raw text null,
  material_raw text null,
  order_code text null,
  source_order_id_raw text null,
  telegram_message_id_raw text null,
  item_label text null,
  plan_value integer null,
  qty_value numeric(12,2) null,
  pilka_started_at_raw text null,
  pilka_finished_at_raw text null,
  pilka_status_raw text null,
  kromka_started_at_raw text null,
  kromka_finished_at_raw text null,
  kromka_executor_raw text null,
  kromka_status_raw text null,
  prisadka_started_at_raw text null,
  prisadka_finished_at_raw text null,
  prisadka_executor_raw text null,
  prisadka_status_raw text null,
  assembly_status_raw text null,
  assembly_time_raw text null,
  notification_raw text null,
  overall_status_raw text null,
  shipped_raw text null,
  source_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (sheet_id, sheet_gid, sheet_row)
);

create index if not exists idx_sheet_orders_mirror_order_code
  on public.sheet_orders_mirror(order_code);

create index if not exists idx_sheet_orders_mirror_overall_status
  on public.sheet_orders_mirror(overall_status_raw);

create or replace function public.trg_sheet_orders_mirror_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_sheet_orders_mirror_touch_updated_at on public.sheet_orders_mirror;
create trigger tr_sheet_orders_mirror_touch_updated_at
before update on public.sheet_orders_mirror
for each row
execute function public.trg_sheet_orders_mirror_touch_updated_at();

create or replace function public.web_norm_sheet_stage_status(p_raw text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(p_raw, '')) like '%готов%' then 'done'
    when lower(coalesce(p_raw, '')) like '%в работе%' then 'in_progress'
    when lower(coalesce(p_raw, '')) like '%пауз%' then 'paused'
    when lower(coalesce(p_raw, '')) like '%новый заказ%' then 'new'
    when lower(coalesce(p_raw, '')) like '%ожидает%' then 'waiting'
    else 'unknown'
  end
$$;

create or replace view public.v_sheet_orders_mirror as
select
  m.sheet_id,
  m.sheet_gid,
  m.sheet_row,
  m.source_created_at_raw,
  m.material_raw,
  m.order_code,
  m.source_order_id_raw,
  m.item_label,
  m.plan_value,
  m.qty_value,
  m.pilka_status_raw,
  public.web_norm_sheet_stage_status(m.pilka_status_raw) as pilka_status,
  m.kromka_status_raw,
  public.web_norm_sheet_stage_status(m.kromka_status_raw) as kromka_status,
  m.prisadka_status_raw,
  public.web_norm_sheet_stage_status(m.prisadka_status_raw) as prisadka_status,
  m.assembly_status_raw,
  public.web_norm_sheet_stage_status(m.assembly_status_raw) as assembly_status,
  m.overall_status_raw,
  public.web_norm_sheet_stage_status(m.overall_status_raw) as overall_status,
  m.shipped_raw,
  m.source_synced_at,
  m.updated_at
from public.sheet_orders_mirror m;

create or replace function public.web_get_sheet_orders_mirror(
  p_sheet_gid text default null
)
returns table(
  sheet_row integer,
  source_created_at_raw text,
  material_raw text,
  order_code text,
  source_order_id_raw text,
  item_label text,
  plan_value integer,
  qty_value numeric,
  pilka_status text,
  kromka_status text,
  prisadka_status text,
  assembly_status text,
  overall_status text,
  shipped_raw text,
  source_synced_at timestamptz
)
language sql
stable
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  select
    v.sheet_row,
    v.source_created_at_raw,
    v.material_raw,
    v.order_code,
    v.source_order_id_raw,
    v.item_label,
    v.plan_value,
    v.qty_value,
    v.pilka_status,
    v.kromka_status,
    v.prisadka_status,
    v.assembly_status,
    v.overall_status,
    v.shipped_raw,
    v.source_synced_at
  from public.v_sheet_orders_mirror v
  where p_sheet_gid is null or trim(p_sheet_gid) = '' or v.sheet_gid = trim(p_sheet_gid)
  order by v.sheet_row;
$$;

grant select on public.sheet_orders_mirror to anon, authenticated, service_role;
grant select on public.v_sheet_orders_mirror to anon, authenticated, service_role;
grant execute on function public.web_get_sheet_orders_mirror(text) to anon, authenticated, service_role;
