-- Queue orders that are blocked by metal component shortages.

create table if not exists public.metal_work_queue (
  id bigint generated by default as identity primary key,
  source_row text not null,
  source_col text not null,
  item text not null,
  week text,
  qty numeric(12,3) not null default 0,
  reason text,
  shortage jsonb not null default '[]'::jsonb,
  status text not null default 'queued' check (status in ('queued', 'in_progress', 'done', 'cancelled')),
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_metal_work_queue_source_active
  on public.metal_work_queue(source_row, source_col)
  where status in ('queued', 'in_progress');

create index if not exists idx_metal_work_queue_status_created
  on public.metal_work_queue(status, created_at desc);

alter table public.metal_work_queue enable row level security;

drop policy if exists metal_work_queue_read_all on public.metal_work_queue;
create policy metal_work_queue_read_all
  on public.metal_work_queue
  for select
  to authenticated
  using (true);

drop policy if exists metal_work_queue_write_admin_manager on public.metal_work_queue;
create policy metal_work_queue_write_admin_manager
  on public.metal_work_queue
  for all
  to authenticated
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

create or replace function public.trg_metal_work_queue_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_metal_work_queue_touch_updated_at on public.metal_work_queue;
create trigger trg_metal_work_queue_touch_updated_at
before update on public.metal_work_queue
for each row
execute function public.trg_metal_work_queue_touch_updated_at();

create or replace function public.web_get_metal_work_queue(
  p_status text default null
)
returns table(
  id bigint,
  source_row text,
  source_col text,
  item text,
  week text,
  qty numeric,
  reason text,
  shortage jsonb,
  status text,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
  select
    q.id,
    q.source_row,
    q.source_col,
    q.item,
    q.week,
    q.qty,
    q.reason,
    q.shortage,
    q.status,
    q.created_at,
    q.updated_at
  from public.metal_work_queue q
  where p_status is null or q.status = p_status
  order by
    case q.status when 'queued' then 0 when 'in_progress' then 1 when 'done' then 2 else 3 end,
    q.created_at desc;
$$;

create or replace function public.web_enqueue_metal_work_order(
  p_source_row text,
  p_source_col text,
  p_item text,
  p_week text,
  p_qty numeric,
  p_reason text default null,
  p_shortage jsonb default '[]'::jsonb
)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_row text := trim(coalesce(p_source_row, ''));
  v_col text := trim(coalesce(p_source_col, ''));
  v_item text := trim(coalesce(p_item, ''));
begin
  perform public.web_require_roles(array['admin', 'manager', 'operator']);
  if v_row = '' or v_col = '' then
    raise exception 'source row/col required';
  end if;
  if v_item = '' then
    raise exception 'item required';
  end if;

  insert into public.metal_work_queue (
    source_row,
    source_col,
    item,
    week,
    qty,
    reason,
    shortage,
    status
  )
  values (
    v_row,
    v_col,
    v_item,
    nullif(trim(coalesce(p_week, '')), ''),
    greatest(coalesce(p_qty, 0), 0),
    nullif(trim(coalesce(p_reason, '')), ''),
    coalesce(p_shortage, '[]'::jsonb),
    'queued'
  )
  on conflict (source_row, source_col) where status in ('queued', 'in_progress')
  do update
  set
    item = excluded.item,
    week = excluded.week,
    qty = excluded.qty,
    reason = excluded.reason,
    shortage = excluded.shortage,
    status = 'queued',
    updated_at = now();
end;
$$;

create or replace function public.web_set_metal_work_queue_status(
  p_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path to 'public', 'extensions', 'pg_temp'
as $$
declare
  v_status text := trim(coalesce(p_status, ''));
begin
  perform public.web_require_roles(array['admin', 'manager', 'operator']);
  if v_status not in ('queued', 'in_progress', 'done', 'cancelled') then
    raise exception 'unsupported status';
  end if;
  update public.metal_work_queue
  set status = v_status,
      updated_at = now()
  where id = p_id;
end;
$$;

grant select on public.metal_work_queue to authenticated, service_role;
grant insert, update on public.metal_work_queue to authenticated, service_role;
grant usage, select on sequence public.metal_work_queue_id_seq to authenticated, service_role;

grant execute on function public.web_get_metal_work_queue(text) to authenticated, service_role;
grant execute on function public.web_enqueue_metal_work_order(text, text, text, text, numeric, text, jsonb) to authenticated, service_role;
grant execute on function public.web_set_metal_work_queue_status(bigint, text) to authenticated, service_role;
